version: "3"
services:
  web:
    build: ./weatherapp
    env_file: .env
    ports:
      - "5002:5000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_database}
    ports:
      - "5433:5432"
